In [90]:
import numpy as np
import pandas as pd
import matplotlib

In [91]:
data = pd.read_excel('final2.xlsx',thousands = ',')

In [92]:
data= pd.DataFrame(data)
#from sklearn.utils import shuffle
#data = data.sample(frac=1).reset_index(drop=True)
data.head(10)

Papers  Specificity  Orientation  Under_Introduction_Section  \
0     K1            1            1                           0   
1     K1            1            1                           0   
2     K1            1            1                           0   
3     K1            1            1                           0   
4     K1            1            1                           0   
5     K1            1            1                           1   
6     K1            1            1                           1   
7     K1            1            1                           1   
8     K1            1            1                           0   
9     K1            1            1                           0   

   Under_Literature_review _section  Under_Theoretical_development_section  \
0                                 0                                      0   
1                                 1                                      1   
2                                 0                                      0   
3                                 0                                      0   
4                                 0                                      0   
5                                 0                                      0   
6                                 0                                      0   
7                                 0                                      0   
8                                 0                                      0   
9                                 1                                      0   

   Under_Methodology  Under_Result_section  Under_the_Discussion_section  \
0                  0                     0                             0   
1                  1                     1                             1   
2                  1                     0                             0   
3                  1                     0                             0   
4                  1                     0                             0   
5                  0                     0                             0   
6                  0                     0                             0   
7                  0                     0                             0   
8                  1                     0                             0   
9                  0                     0                             0   

   Under_Implication_Contributuion_Section  ...   A14  A15  A16  A17  A18  \
0                                        0  ...   0.0  0.0  0.0  0.0  0.0   
1                                        1  ...   0.0  0.0  0.0  0.0  0.0   
2                                        0  ...   0.0  0.0  0.0  0.0  0.0   
3                                        0  ...   0.0  0.0  0.0  0.0  0.0   
4                                        0  ...   0.0  0.0  0.0  0.0  0.0   
5                                        0  ...   0.0  0.0  0.0  0.0  0.0   
6                                        0  ...   0.0  0.0  0.0  0.0  0.0   
7                                        0  ...   0.0  0.0  0.0  0.0  0.0   
8                                        0  ...   0.0  0.0  0.0  0.0  0.0   
9                                        0  ...   1.0  0.0  0.0  0.0  0.0   

   A19  A20  A21  Total_years  Rank  
0  0.0  0.0  0.0           14   1.0  
1  0.0  0.0  1.0            4   3.0  
2  0.0  0.0  0.0            4   3.0  
3  0.0  0.0  0.0            5   3.0  
4  0.0  0.0  0.0            4   3.0  
5  0.0  0.0  1.0           12   2.0  
6  0.0  0.0  1.0           10   2.0  
7  0.0  0.0  1.0            5   2.0  
8  0.0  0.0  0.0            9   3.0  
9  0.0  0.0  0.0            8   1.0  

[10 rows x 44 columns]

In [93]:
#X = data.drop(['Rank','Papers','Specificity','Orientation','Under_Implication_Contributuion_Section','Cited_in_different_section','A11','A16','A17','A21'],axis=1)
X = data.drop(['Rank','Papers','Year','Under_the_Discussion_section','Part_of_a_cluster_ of_citation',
               'Pubjished_in_the_same_journal', 'Total_Number_of_Authors',
               'A5','A16','A17','A20','Total_years'],axis=1)


In [94]:
import statsmodels.api as sm
X = sm.add_constant(X)
Y = data['Rank'] 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

In [95]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
X_train = X_train.select_dtypes(include=[np.number])
X_test = X_test.select_dtypes(include=[np.number])

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('std_scaler', StandardScaler()),
    ])

X_train_Scalar = num_pipeline.fit_transform(X_train)
print(X_train_Scalar)

X_test_Scalar = num_pipeline.fit_transform(X_test)
print(X_test_Scalar)

print(X_train_Scalar.shape,X_test_Scalar.shape)
print(Y_train.shape,Y_test.shape)

X_train=np.concatenate([X_train_Scalar],axis=1)
X_train=pd.DataFrame(X_train)

X_test=np.concatenate([X_test_Scalar],axis=1)
X_test=pd.DataFrame(X_test)
print(type(X_train),type(X_test))

[[ 0.         -0.2965667   0.07461855 ... -0.11104881 -0.12996881
  -0.37244294]
 [ 0.         -0.2965667   0.07461855 ... -0.11104881 -0.12996881
  -0.37244294]
 [ 0.         -0.2965667   0.07461855 ... -0.11104881 -0.12996881
  -0.37244294]
 ...
 [ 0.         -0.2965667   0.07461855 ... -0.11104881 -0.12996881
  -0.37244294]
 [ 0.          3.37192275  0.07461855 ... -0.11104881 -0.12996881
   2.68497503]
 [ 0.         -0.2965667   0.07461855 ... -0.11104881 -0.12996881
  -0.37244294]]
[[ 0.         -0.28520118  0.         ... -0.06666667 -0.1159867
  -0.44245587]
 [ 0.         -0.28520118  0.         ... -0.06666667 -0.1159867
  -0.44245587]
 [ 0.          3.50629686  0.         ... -0.06666667  8.6216781
  -0.44245587]
 ...
 [ 0.         -0.28520118  0.         ... -0.06666667 -0.1159867
  -0.44245587]
 [ 0.         -0.28520118  0.         ... -0.06666667 -0.1159867
  -0.44245587]
 [ 0.         -0.28520118  0.         ... -0.06666667 -0.1159867
  -0.44245587]]
(903, 33) (226, 33)
(9

In [96]:
np.isnan(X_train).any(), np.isnan(Y_train).any(), np.isnan(X_test).any()
X_train[np.isnan(X_train)] = np.median(X_train[~np.isnan(X_train)])
Y_train[np.isnan(Y_train)] = np.median(Y_train[~np.isnan(Y_train)])
Y_test[np.isnan(Y_test)] = np.median(Y_test[~np.isnan(Y_test)])

In [97]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver="liblinear", random_state=42)
# same for solver='newton-cg'

log_predict=log_reg.fit(X_train, Y_train).predict(X_test)
#print(log_predict)

from sklearn.metrics import accuracy_score
print("Accuracy: ",accuracy_score(Y_test, log_predict))
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, log_predict)
from sklearn.metrics import classification_report
print(classification_report(Y_test, log_predict))
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(Y_test, log_predict)
print("RMSE:",rmse)
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(Y_test, log_predict)
print("Confusion matrix:\n",confusion)

Accuracy:  0.6548672566371682
              precision    recall  f1-score   support

         1.0       0.69      0.71      0.70        68
         2.0       0.60      0.51      0.55        72
         3.0       0.67      0.73      0.70        86

   micro avg       0.65      0.65      0.65       226
   macro avg       0.65      0.65      0.65       226
weighted avg       0.65      0.65      0.65       226

RMSE: 0.584070796460177
Confusion matrix:
 [[48 13  7]
 [11 37 24]
 [11 12 63]]


/Users/shailysaigal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [98]:
from sklearn.svm import SVC
svr_rbf = SVC(kernel='rbf', C=4,gamma='scale',random_state=42)
y_rbf = svr_rbf.fit(X_train, Y_train).predict(X_test)

print("Accuracy: ",accuracy_score(Y_test, y_rbf))
confusion_matrix(Y_test, y_rbf)
print(classification_report(Y_test, y_rbf))
rmse = mean_squared_error(Y_test, y_rbf)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, y_rbf)
print("Confusion matrix:\n",confusion)

Accuracy:  0.7433628318584071
              precision    recall  f1-score   support

         1.0       0.76      0.76      0.76        68
         2.0       0.72      0.68      0.70        72
         3.0       0.74      0.78      0.76        86

   micro avg       0.74      0.74      0.74       226
   macro avg       0.74      0.74      0.74       226
weighted avg       0.74      0.74      0.74       226

RMSE: 0.4690265486725664
Confusion matrix:
 [[52 10  6]
 [ 6 49 17]
 [10  9 67]]


In [111]:
from sklearn.svm import SVC
svr = SVC(kernel='linear', C=0.5,gamma='scale',random_state=42)
y_lin = svr.fit(X_train, Y_train).predict(X_test)

print("Accuracy: ",accuracy_score(Y_test, y_lin))
confusion_matrix(Y_test, y_lin)
print(classification_report(Y_test, y_lin))
rmse = mean_squared_error(Y_test, y_lin)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, y_lin)
print("Confusion matrix:\n",confusion)

Accuracy:  0.668141592920354
              precision    recall  f1-score   support

         1.0       0.64      0.82      0.72        68
         2.0       0.70      0.43      0.53        72
         3.0       0.68      0.74      0.71        86

   micro avg       0.67      0.67      0.67       226
   macro avg       0.67      0.67      0.65       226
weighted avg       0.68      0.67      0.66       226

RMSE: 0.6106194690265486
Confusion matrix:
 [[56  5  7]
 [18 31 23]
 [14  8 64]]


In [88]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=5, random_state=42,min_samples_leaf=3)
dec_tree=tree_clf.fit(X_train, Y_train).predict(X_test)

print("Accuracy: ",accuracy_score(Y_test, dec_tree))
confusion_matrix(Y_test,dec_tree)
print(classification_report(Y_test, dec_tree))
rmse = mean_squared_error(Y_test, dec_tree)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, dec_tree)
print("Confusion matrix:\n",confusion)

Accuracy:  0.6061946902654868
              precision    recall  f1-score   support

         1.0       0.45      0.90      0.60        51
         2.0       0.78      0.25      0.38        85
         3.0       0.72      0.78      0.75        90

   micro avg       0.61      0.61      0.61       226
   macro avg       0.65      0.64      0.57       226
weighted avg       0.68      0.61      0.57       226

RMSE: 0.6460176991150443
Confusion matrix:
 [[46  1  4]
 [41 21 23]
 [15  5 70]]


In [89]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

log_clf = LogisticRegression(solver="liblinear", random_state=42)
rnd_clf = RandomForestClassifier(n_estimators=6, random_state=42)
svm_clf = SVC(gamma="auto", random_state=42,probability=True)

voting_clf = VotingClassifier(
    estimators=[ ('lr', log_clf),('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')

voting_clf.fit(X_train, Y_train)
for clf in (log_clf, svm_clf,rnd_clf, voting_clf):
    clf.fit(X_train, Y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(Y_test, y_pred))
    confusion_matrix(Y_test,y_pred)
    print(classification_report(Y_test, y_pred))
    rmse = mean_squared_error(Y_test, y_pred)
    print("RMSE:",rmse)
    confusion = confusion_matrix(Y_test, y_pred)
    print("Confusion matrix:\n",confusion)
    print("\n")
   

/Users/shailysaigal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/shailysaigal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression 0.6017699115044248
              precision    recall  f1-score   support

         1.0       0.51      0.76      0.61        51
         2.0       0.57      0.45      0.50        85
         3.0       0.71      0.66      0.68        90

   micro avg       0.60      0.60      0.60       226
   macro avg       0.60      0.62      0.60       226
weighted avg       0.61      0.60      0.60       226

RMSE: 0.584070796460177
Confusion matrix:
 [[39  7  5]
 [28 38 19]
 [ 9 22 59]]


SVC 0.6283185840707964
              precision    recall  f1-score   support

         1.0       0.58      0.73      0.64        51
         2.0       0.63      0.48      0.55        85
         3.0       0.66      0.71      0.68        90

   micro avg       0.63      0.63      0.63       226
   macro avg       0.62      0.64      0.62       226
weighted avg       0.63      0.63      0.62       226

RMSE: 0.584070796460177
Confusion matrix:
 [[37  6  8]
 [19 41 25]
 [ 8 18 64]]


RandomForestC

/Users/shailysaigal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


VotingClassifier 0.6194690265486725
              precision    recall  f1-score   support

         1.0       0.54      0.75      0.62        51
         2.0       0.61      0.44      0.51        85
         3.0       0.69      0.72      0.71        90

   micro avg       0.62      0.62      0.62       226
   macro avg       0.61      0.63      0.61       226
weighted avg       0.62      0.62      0.61       226

RMSE: 0.5663716814159292
Confusion matrix:
 [[38  7  6]
 [25 37 23]
 [ 8 17 65]]




In [77]:
from sklearn.ensemble import BaggingClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(splitter="random", max_leaf_nodes=16,random_state=42), n_estimators=500,
    max_samples=1.0, random_state=42)

bag_clf.fit(X_train, Y_train)
y_pred_bag = bag_clf.predict(X_test)
print("Accuracy: ",accuracy_score(Y_test, y_pred_bag))
confusion_matrix(Y_test,y_pred_bag)
print(classification_report(Y_test, y_pred_bag))
rmse = mean_squared_error(Y_test, y_pred_bag)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, y_pred_bag)
print("Confusion matrix:\n",confusion)

Accuracy:  0.6504424778761062
              precision    recall  f1-score   support

         1.0       0.64      0.79      0.71        68
         2.0       0.72      0.36      0.48        72
         3.0       0.64      0.78      0.70        86

   micro avg       0.65      0.65      0.65       226
   macro avg       0.67      0.64      0.63       226
weighted avg       0.66      0.65      0.63       226

RMSE: 0.6548672566371682
Confusion matrix:
 [[54  4 10]
 [18 26 28]
 [13  6 67]]


In [78]:
rnd_clf = RandomForestClassifier(n_estimators=3, random_state=42)

rnd_clf.fit(X_train, Y_train)
y_pred1 = bag_clf.predict(X_test)
print("Accuracy: ",accuracy_score(Y_test, y_pred1)) 
confusion_matrix(Y_test,y_pred1)
print(classification_report(Y_test, y_pred1))
rmse = mean_squared_error(Y_test, y_pred1)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, y_pred1)
print("Confusion matrix:\n",confusion)

Accuracy:  0.6504424778761062
              precision    recall  f1-score   support

         1.0       0.64      0.79      0.71        68
         2.0       0.72      0.36      0.48        72
         3.0       0.64      0.78      0.70        86

   micro avg       0.65      0.65      0.65       226
   macro avg       0.67      0.64      0.63       226
weighted avg       0.66      0.65      0.63       226

RMSE: 0.6548672566371682
Confusion matrix:
 [[54  4 10]
 [18 26 28]
 [13  6 67]]


In [79]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=4), n_estimators=400,
    algorithm="SAMME.R", learning_rate=0.3, random_state=42)

ada=ada_clf.fit(X_train, Y_train).predict(X_test)
print("Accuracy: ",accuracy_score(Y_test, ada))
confusion_matrix(Y_test,ada)
print(classification_report(Y_test, ada))
rmse = mean_squared_error(Y_test, ada)
print("RMSE:",rmse)
confusion = confusion_matrix(Y_test, ada)
print("Confusion matrix:\n",confusion)

Accuracy:  0.584070796460177
              precision    recall  f1-score   support

         1.0       0.63      0.46      0.53        68
         2.0       0.44      0.54      0.49        72
         3.0       0.70      0.72      0.71        86

   micro avg       0.58      0.58      0.58       226
   macro avg       0.59      0.57      0.58       226
weighted avg       0.60      0.58      0.58       226

RMSE: 0.5752212389380531
Confusion matrix:
 [[31 29  8]
 [14 39 19]
 [ 4 20 62]]
